
POST http://localhost:3000/cadastro
Content-Type: application/json

{
    "name": 2,
    "email": "caroline@gmail.com",
    "telefone": "81989447610",
    "profissao": "eletricista"
}
###
PUT http://localhost:3000/editar/1
Content-Type: application/json

{
    name": "Teste",
    "email": "teste.teste.teste@gmail.com",
    "telefone": "teste",
    "profissao": "tester"
}
###
GET http://localhost:3000/
###
PATCH http://localhost:3000/editar/9
Content-Type: application/json

{
    "email": "paulo.guilherme.arruda1@gmail.com"
}
###
DELETE http://localhost:3000/delete/10
###
