POST http://localhost:3000/cadastro
Content-Type: application/json

{
    "name": "Carol",
    "email": "asdas",
    "telefone": "asdas",
    "profissao": "asdas"
}
###
PUT http://localhost:3000/editar/1
Content-Type: application/json

{
    name": "Teste",
    "email": "teste.teste.teste@gmail.com",
    "telefone": "teste",
    "profissao": "tester"
}
###
GET http://localhost:3000/1
###
PUT http://localhost:3000/editar/1 
Content-Type: application/json

{
    "name": "Paulo Guilherme"
}
###
DELETE http://localhost:3000/delete/8
###
